services:
  botgarden-web:
    build: .
    container_name: botgarden-web
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Optional: SSL with Let's Encrypt (for production)
# Uncomment and configure for HTTPS
#
# services:
#   botgarden-web:
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./certs:/etc/nginx/certs:ro
#       - ./nginx-ssl.conf:/etc/nginx/nginx.conf:ro
